#!/usr/bin/env python3
"""P4 of analyses/perturbation_tests: replicate the Enformer all-site promoter occlusion with Borzoi.

Inputs, exactly those of the Enformer run:
  - the 1,626 calls of results/v3/seqreg_ext_occlusion_allsites.csv (618 COL1A1, 1,008 COL3A1), taken from
    results/v3/seqreg_motif_sites.csv in the same order;
  - 5 dinucleotide-preserving shuffles per call.  The shuffles are regenerated by replaying the random stream of
    scripts/09_regulatory_evidence/sequence_models/41_seqreg_ext_occlusion_null.py verbatim: random.Random(20260910), its dinuc_shuffle(), its Enformer
    window, and every draw of its experiment 2 (distal peaks and controls), which sits between the COL1A1 and COL3A1
    calls.  The replay is checked by re-predicting calls with Enformer and comparing with the deposited values
    (p4_replay_check.csv) before Borzoi runs;
  - the point-mutation controls of scripts/09_regulatory_evidence/sequence_models/45_seqreg_ext_splicedonor_control.py (donor GT->AA and GT->CC,
    GGAA->CCTT and GGAA->TTTT at COL3A1, the 4-bp exonic control).
Borzoi: borzoi-pytorch port of the official human weights, replicates 0-3, bf16 autocast, batch size 1, input 524,288
bp centred on the same anchor (the Enformer window is its central 196,608 bp, so every site keeps its genomic position).
Tracks (p4_tracks.tsv, written before any prediction): every Borzoi RNA and CAGE track whose description contains
"ibroblast", the selection rule of the Enformer scripts.  Stranded pairs are summed over both strands and count as one
track (as baskerville's targets_prep_strand does).  Borzoi's squashed scale is undone per track (old transform of
borzoi_pytorch.undo_squashed_scale: /scale, unclip above clip_soft, **(4/3) for sum_sqrt tracks).
Scores per sequence and replicate:
  RNA  = mean over RNA tracks of the undone coverage summed over the bins overlapping the exons of the RefSeq Select
         transcript (NM_000088.4, NM_000090.4);
  CAGE = mean over CAGE tracks of the undone coverage summed over the 12 bins (384 bp) centred on the TSS, the span of
         the Enformer score (3 x 128-bp bins).
Effect of a call = mean over its 5 shuffles of (score - reference score), per replicate, then averaged over replicates.
Replicates run one after another (all sequences with replicate 0, then 1, 2, 3), with per-replicate checkpoints, so
a stop after two replicates leaves complete two-replicate results.
usage: p4_borzoi_occlusion.py [--reps 0,1,2,3] [--check-only]"""
import os, sys, time, random, argparse, subprocess, json
import numpy as np, pandas as pd, torch

OUT = os.path.dirname(os.path.abspath(__file__))
INB = os.path.dirname(OUT); REV = os.path.dirname(os.path.dirname(INB))
RES, CACHE = f"{REV}/results/v3", f"{REV}/cache/seqreg"
HF27 = f"{REV}/data_cache/huggingface"
ap = argparse.ArgumentParser(); ap.add_argument('--reps', default='0,1,2,3'); ap.add_argument('--check-only', action='store_true')
ap.add_argument('--bench', action='store_true')
A = ap.parse_args(); REPS = [int(x) for x in A.reps.split(',')]
LOG = open(f"{OUT}/p4_run.log", 'a')
def log(*a):
    s = time.strftime('%Y-%m-%d %H:%M:%S ') + ' '.join(str(x) for x in a)
    print(s, flush=True); LOG.write(s + '\n'); LOG.flush()
def gpu_reading(tag):
    q = subprocess.run("nvidia-smi --query-gpu=memory.used,memory.total,utilization.gpu,power.draw,temperature.gpu --format=csv,noheader", shell=True, capture_output=True, text=True).stdout.strip()
    apps = subprocess.run("nvidia-smi --query-compute-apps=pid,process_name,used_memory --format=csv,noheader", shell=True, capture_output=True, text=True).stdout.strip()
    open(f"{OUT}/p4_gpu_log.txt", 'a').write(f"{time.strftime('%Y-%m-%d %H:%M:%S')}\t{tag}\t{q}\tcompute processes: {apps or 'none'}\n")
    return apps

# ------------------------------------------------------------------ replay of 41_ (verbatim geometry and stream)
E_SEQ_LEN, HALF = 196_608, 300_000
N_SHUF, N_SHUF_PEAK, N_CTRL, N_SHUF_CTRL = 5, 5, 20, 2
reg = pd.read_csv(f"{RES}/seqreg_regions.csv").set_index("region")
def revcomp(s): return s.translate(str.maketrans("ACGTN", "TGCAN"))[::-1]
rng = random.Random(20260910)
def dinuc_shuffle(s):
    if len(s) < 3:
        return s
    for _ in range(50):
        edges = {}
        for a, b in zip(s, s[1:]):
            edges.setdefault(a, []).append(b)
        for k in edges:
            rng.shuffle(edges[k])
        out = [s[0]]; cur = s[0]; ok = True
        for _ in range(len(s) - 1):
            if not edges.get(cur):
                ok = False; break
            nxt = edges[cur].pop(); out.append(nxt); cur = nxt
        if ok and len(out) == len(s):
            return "".join(out)
    return "".join(rng.sample(s, len(s)))
def full_locus(regname):
    r = reg.loc[regname]; a = int(r.anchor)
    return open(f"{CACHE}/seq/{r.chrom}_{a - HALF}_{a + HALF}.txt").read().strip(), r.strand, r.chrom, a
sites = pd.read_csv(f"{RES}/seqreg_motif_sites.csv")
sites["tf_name"] = sites.motif.str.split("|").str[-1].str.split("_HUMAN").str[0]
peaks = pd.read_csv(f"{RES}/seqreg_rela_fibroblast_peaks.csv")
dep = pd.read_csv(f"{RES}/seqreg_ext_occlusion_allsites.csv")
CALLS = []            # dict per call: region, n, lo/hi in the ENFORMER window, 5 shuffled strings (window orientation)
for regname in ["COL1A1", "COL3A1"]:
    full, strand, chrom, anchor = full_locus(regname)
    ref = full[HALF - E_SEQ_LEN // 2: HALF + E_SEQ_LEN // 2]
    ss = sites[sites.region == regname].reset_index(drop=True)
    for n, (_, r) in enumerate(ss.iterrows()):
        rel = int(r.rel_to_TSS); L = len(str(r.seq))
        i = E_SEQ_LEN // 2 + (rel if strand == "+" else -rel)
        lo, hi = (i, i + L) if strand == "+" else (i - L + 1, i + 1)
        wt = ref[lo:hi]; shs = []
        for _ in range(N_SHUF):
            sh = dinuc_shuffle(wt if strand == "+" else revcomp(wt))
            if strand == "-":
                sh = revcomp(sh)
            shs.append(sh)
        CALLS.append(dict(region=regname, n=n, db=r.db, motif=r.motif, tf_name=r.tf_name, rel_to_TSS=rel, site_len=L, lo=lo, hi=hi, shuffles=shs))
    # experiment 2: consume the stream exactly as 41_ did (no predictions needed)
    pk = peaks[peaks.gene == regname].reset_index(drop=True)
    forbidden = []
    for _, r in pk.iterrows():
        lo = int(r.start) - (anchor - E_SEQ_LEN // 2)
        forbidden.append((lo, lo + int(r.width)))
    prom_i = E_SEQ_LEN // 2
    for _, r in pk.iterrows():
        w = int(r.width); lo = int(r.start) - (anchor - E_SEQ_LEN // 2); hi = lo + w
        if lo < 0 or hi > E_SEQ_LEN:
            continue
        wt = ref[lo:hi]
        _ = [dinuc_shuffle(wt) for _ in range(N_SHUF_PEAK)]
        ncd = 0; tries = 0
        while ncd < N_CTRL and tries < 2000:
            tries += 1
            c = rng.randrange(prom_i - 98_000, prom_i + 98_000 - w)
            if abs(c - prom_i) < 1500:
                continue
            if any(not (c + w <= a or c >= b2) for a, b2 in forbidden):
                continue
            cwt = ref[c:c + w]
            if cwt.count("N") > 0:
                continue
            _ = [dinuc_shuffle(cwt) for _ in range(N_SHUF_CTRL)]
            ncd += 1
# the replayed calls must be the deposited calls, in order
assert len(CALLS) == len(dep) == 1626
for c, (_, d) in zip(CALLS, dep.iterrows()):
    assert (c['region'], c['motif'], c['rel_to_TSS']) == (d.region, d.motif, int(d.rel_to_TSS)), (c['region'], c['n'])
pd.DataFrame([dict(region=c['region'], n=c['n'], motif=c['motif'], rel_to_TSS=c['rel_to_TSS'], **{f'shuffle_{k}': s for k, s in enumerate(c['shuffles'])})
              for c in CALLS]).to_csv(f"{OUT}/p4_shuffles.tsv.gz", sep='\t', index=False, compression='gzip')
log(f"replayed {len(CALLS)} calls x {N_SHUF} shuffles; order matches the deposited table")

# ------------------------------------------------------------------ Enformer check of the replay
check_path = f"{OUT}/p4_replay_check.csv"
if not os.path.exists(check_path):
    from enformer_pytorch import from_pretrained
    etg = pd.read_csv(f"{CACHE}/enformer_targets_human.txt", sep="\t"); etg["assay"] = etg.description.str.split(":").str[0]
    FIB_CAGE = etg.index[(etg.assay == "CAGE") & etg.description.str.contains("ibroblast")].to_numpy()
    E_BINS, E_BIN = 896, 128; E_CROP = (E_SEQ_LEN - E_BINS * E_BIN) // 2; E_CB = (E_SEQ_LEN // 2 - E_CROP) // E_BIN
    MAP = {"A": 0, "C": 1, "G": 2, "T": 3}
    def onehot_e(s):
        a = np.zeros((len(s), 4), dtype=np.float32); idx = np.frombuffer(s.encode(), dtype=np.uint8)
        for b, i in MAP.items(): a[idx == ord(b), i] = 1.0
        return a
    em = from_pretrained("EleutherAI/enformer-official-rough").eval().cuda()
    @torch.no_grad()
    def e_fib(seqs):
        outs = []
        for k in range(0, len(seqs), 2):                 # BATCH = 2, as in 41_
            x = torch.from_numpy(np.stack([onehot_e(s) for s in seqs[k:k + 2]])).cuda()
            with torch.autocast("cuda", dtype=torch.bfloat16):
                o = em(x)["human"]
            outs.append(o.float().cpu().numpy())
        p = np.concatenate(outs, 0)[:, E_CB - 1:E_CB + 2, :].mean(1)
        return p[:, FIB_CAGE].mean(1)
    rows = []
    for regname in ["COL1A1", "COL3A1"]:
        full, strand, chrom, anchor = full_locus(regname)
        ref = full[HALF - E_SEQ_LEN // 2: HALF + E_SEQ_LEN // 2]
        g = [c for c in CALLS if c['region'] == regname]
        dg = dep[dep.region == regname].reset_index(drop=True)
        pick = sorted(set([0, 1] + list(dg.nsmallest(5, 'd_fib_cage').index)))
        for n in pick:
            c = g[n]; seqs = [ref[:c['lo']] + s + ref[c['hi']:] for s in c['shuffles']]
            v = float(e_fib(seqs).mean())
            rows.append(dict(region=regname, n=n, motif=c['motif'], rel_to_TSS=c['rel_to_TSS'], deposited_mean_shuffled_fib_cage=float(dg.loc[n, 'mean_shuffled_fib_cage']),
                             replayed_mean_shuffled_fib_cage=v, abs_diff=abs(v - float(dg.loc[n, 'mean_shuffled_fib_cage'])),
                             deposited_d=float(dg.loc[n, 'd_fib_cage'])))
            log('replay check', rows[-1])
    pd.DataFrame(rows).to_csv(check_path, index=False)
    del em; torch.cuda.empty_cache()
chk = pd.read_csv(check_path)
tol = 0.001 * chk.deposited_mean_shuffled_fib_cage.abs()
log(f"replay check: {int((chk.abs_diff <= tol).sum())}/{len(chk)} calls within 0.1 % of the deposited Enformer value; max abs diff {chk.abs_diff.max():.4g}")
if not (chk.abs_diff <= tol).all():
    log("REPLAY CHECK FAILED: the regenerated shuffles do not reproduce the Enformer run; stopping"); sys.exit(2)
if A.check_only: sys.exit(0)

# ------------------------------------------------------------------ Borzoi set-up
from borzoi_pytorch import Borzoi
B_SEQ_LEN, N_BINS, BIN = 524_288, 6144, 32
CROP = (B_SEQ_LEN - N_BINS * BIN) // 2; OFF = (B_SEQ_LEN - E_SEQ_LEN) // 2
tg = pd.read_csv(f"{CACHE}/borzoi_targets_human.txt", sep="\t"); tg["assay"] = tg.description.str.split(":").str[0]
sel = tg[tg.description.str.contains("ibroblast") & tg.assay.isin(["RNA", "CAGE"])].copy()
sel['pair_key'] = [min(i, int(p)) if int(p) != i else i for i, p in zip(sel.index, sel.strand_pair)]
sel['track_transform'] = np.where(sel.sum_stat.str.contains('sqrt'), 0.75, 1.0)
sel[['identifier', 'assay', 'description', 'clip', 'clip_soft', 'scale', 'sum_stat', 'strand_pair', 'pair_key', 'track_transform']].to_csv(f"{OUT}/p4_tracks.tsv", sep='\t', index_label='track_index')
IDX = sel.index.to_numpy()
cs = sel.clip_soft.to_numpy()[None, :].astype(np.float64); sc = sel.scale.to_numpy()[None, :].astype(np.float64); tt = sel.track_transform.to_numpy()[None, :]
def pairs_of(assay):
    keys = sorted(set(sel.pair_key[sel.assay == assay])); return [np.where((sel.pair_key == k).to_numpy())[0] for k in keys]
PAIRS = {a: pairs_of(a) for a in ('RNA', 'CAGE')}
log(f"tracks: RNA {int((sel.assay == 'RNA').sum())} ({len(PAIRS['RNA'])} after strand pairing); CAGE {int((sel.assay == 'CAGE').sum())} ({len(PAIRS['CAGE'])} after strand pairing)")
rs = pd.read_csv(f"{CACHE}/genome/ncbiRefSeqSelect.txt.gz", sep="\t", header=None,
                 names=["bin", "name", "chrom", "strand", "txStart", "txEnd", "cdsStart", "cdsEnd", "exonCount", "exonStarts", "exonEnds", "score", "name2", "cdsStartStat", "cdsEndStat", "exonFrames"])
GENE = {}
for regname, acc in (("COL1A1", "NM_000088.4"), ("COL3A1", "NM_000090.4")):
    r = reg.loc[regname]; t = rs[(rs.name == acc) & (rs.chrom == r.chrom)].iloc[0]
    a = int(r.anchor); w0 = a - B_SEQ_LEN // 2 + CROP            # genomic position of output bin 0
    ex = [(int(s), int(e)) for s, e in zip(t.exonStarts.strip(',').split(','), t.exonEnds.strip(',').split(','))]
    bins = sorted({b for s, e in ex for b in range((s - w0) // BIN, (e - 1 - w0) // BIN + 1) if 0 <= b < N_BINS})
    tss_bin = (a - w0) // BIN
    GENE[regname] = dict(exon_bins=np.array(bins), tss_bins=np.arange(tss_bin - 6, tss_bin + 6), n_exons=len(ex))
    log(f"{regname}: {len(ex)} exons -> {len(bins)} exon bins; TSS bin {tss_bin}")
json.dump({k: dict(exon_bins=v['exon_bins'].tolist(), tss_bins=v['tss_bins'].tolist(), n_exons=v['n_exons']) for k, v in GENE.items()}, open(f"{OUT}/p4_bins.json", 'w'))
MAP = {"A": 0, "C": 1, "G": 2, "T": 3}
def onehot(s):
    a = np.zeros((4, len(s)), dtype=np.float32); idx = np.frombuffer(s.encode(), dtype=np.uint8)
    for b, i in MAP.items(): a[i, idx == ord(b)] = 1.0
    return a
def undo(x):                                                   # x: bins x selected tracks
    x = x.astype(np.float64) / sc
    m = x > cs; x = np.where(m, (x - cs) ** 2 + cs, x)
    return x ** (1.0 / tt)
def scores(x, regname):
    u = undo(x); g = GENE[regname]
    rna = np.mean([u[g['exon_bins']][:, p].sum() for p in PAIRS['RNA']])
    cage = np.mean([u[g['tss_bins']][:, p].sum() for p in PAIRS['CAGE']])
    return rna, cage
def load_rep(r):
    kw = {} if r == 0 else dict(cache_dir=HF27)
    m = Borzoi.from_pretrained(f'johahi/borzoi-replicate-{r}', low_cpu_mem_usage=False, **kw)
    fresh = Borzoi(m.config); fb = dict(fresh.named_buffers()); nfix = 0
    for name, buf in list(m.named_buffers()):
        if buf.is_meta:
            mod = m; parts = name.split('.')
            for pp in parts[:-1]: mod = getattr(mod, pp)
            setattr(mod, parts[-1], fb[name].clone()); nfix += 1
    assert not any(b.is_meta for _, b in m.named_buffers())
    del fresh
    return m.eval().cuda(), nfix
IDX_T = torch.from_numpy(IDX).cuda()
@torch.no_grad()
def predict(model, seq):
    x = torch.from_numpy(onehot(seq)).unsqueeze(0).cuda()
    with torch.autocast('cuda', dtype=torch.bfloat16):
        o = model(x)
    o = o[0]
    if o.shape[0] != N_BINS: o = o.T                                # -> bins x tracks
    return o[:, IDX_T].float().cpu().numpy()

# sequences: per region the reference, the 45_ controls, then every call's 5 shuffles
def put(ref, rel, strand, newbases, anchor_idx):
    s = list(ref)
    for k, b in enumerate(newbases):
        i = anchor_idx + (rel + k if strand == "+" else -(rel + k))
        s[i] = b if strand == "+" else revcomp(b)
    return "".join(s)
def read(ref, rel, strand, n, anchor_idx):
    return "".join(ref[anchor_idx + (rel + k)] if strand == "+" else revcomp(ref[anchor_idx - (rel + k)]) for k in range(n))
LOCI = {"COL3A1": dict(last_exonic=195, ggaa_start=191), "COL1A1": dict(last_exonic=221, ggaa_start=None)}
SEQS = []                                                         # (key, region, sequence)
for regname in ["COL1A1", "COL3A1"]:
    full, strand, chrom, anchor = full_locus(regname)
    bref = full[HALF - B_SEQ_LEN // 2: HALF + B_SEQ_LEN // 2]; assert len(bref) == B_SEQ_LEN
    ai = B_SEQ_LEN // 2
    SEQS.append((f"{regname}|ref", regname, bref))
    cfg = LOCI[regname]; le = cfg["last_exonic"]
    donor = read(bref, le + 1, strand, 2, ai)
    SEQS.append((f"{regname}|ctrl|donor_kill_GT_to_AA|TSS+{le+1}..+{le+2} {donor}->AA", regname, put(bref, le + 1, strand, "AA", ai)))
    SEQS.append((f"{regname}|ctrl|donor_kill_GT_to_CC|TSS+{le+1}..+{le+2} {donor}->CC", regname, put(bref, le + 1, strand, "CC", ai)))
    if cfg["ggaa_start"] is not None:
        gs = cfg["ggaa_start"]; core = read(bref, gs, strand, 4, ai)
        SEQS.append((f"{regname}|ctrl|ets_core_kill_GGAA_to_CCTT|TSS+{gs}..+{gs+3} {core}->CCTT", regname, put(bref, gs, strand, "CCTT", ai)))
        SEQS.append((f"{regname}|ctrl|ets_core_kill_GGAA_to_TTTT|TSS+{gs}..+{gs+3} {core}->TTTT", regname, put(bref, gs, strand, "TTTT", ai)))
    csx = le - 25; ctrl = read(bref, csx, strand, 4, ai)
    SEQS.append((f"{regname}|ctrl|exonic_control_4bp|TSS+{csx}..+{csx+3} {ctrl}->neutral", regname,
                 put(bref, csx, strand, "".join("A" if b != "A" else "C" for b in ctrl), ai)))
    for c in [c for c in CALLS if c['region'] == regname]:
        for k, s in enumerate(c['shuffles']):
            lo, hi = c['lo'] + OFF, c['hi'] + OFF
            assert bref[lo:hi] == full[HALF - E_SEQ_LEN // 2:][c['lo']:c['hi']]
            SEQS.append((f"{regname}|call|{c['n']}|{k}", regname, bref[:lo] + s + bref[hi:]))
log(f"sequences per replicate: {len(SEQS)}")

# ------------------------------------------------------------------ run, one replicate at a time
apps = gpu_reading('before start')
log(f"GPU compute processes before start: {apps or 'none'}")
for r in REPS:
    ck = f"{OUT}/p4_scores_rep{r}.tsv"
    done = set(pd.read_csv(ck, sep='\t').key) if os.path.exists(ck) else set()
    if len(done) >= len(SEQS): log(f"replicate {r}: complete ({len(done)})"); continue
    model, nfix = load_rep(r); log(f"replicate {r}: loaded (rebuilt {nfix} meta buffers)")
    fh = open(ck, 'a')
    if not done: fh.write('key\tregion\trna_exon_sum\tcage_tss_sum\n')
    t0 = time.time(); k0 = 0
    for key, regname, s in SEQS:
        if key in done: continue
        rna, cage = scores(predict(model, s), regname)
        fh.write(f"{key}\t{regname}\t{rna!r}\t{cage!r}\n"); k0 += 1
        if k0 % 50 == 0:
            fh.flush(); el = time.time() - t0
            log(f"replicate {r}: {len(done) + k0}/{len(SEQS)} sequences, {el / k0:.3f} s per sequence")
            if k0 % 500 == 0: gpu_reading(f'replicate {r} at {len(done) + k0}')
        if A.bench and k0 >= 20:
            log(f"BENCH replicate {r}: {k0} sequences in {time.time() - t0:.1f} s = {(time.time() - t0) / k0:.3f} s each"); sys.exit(0)
    fh.close(); log(f"replicate {r}: finished in {(time.time() - t0) / 3600:.2f} h")
    del model; torch.cuda.empty_cache()
gpu_reading('after last replicate')
log("DONE")
