#!/usr/bin/env Rscript
## PART 2I, named-method run: CellChat v2 on the Human Breast Cancer Single Cell Atlas
## (subsampled), CAF subtypes -> cancer cells, with the ECM/collagen and TGF-beta pathways
## reported explicitly.
suppressPackageStartupMessages({library(CellChat); library(Matrix); library(data.table)})
set.seed(20260909)
REV <- "/path/to/revision"; OUT <- file.path(REV,"results/v3")
msg <- function(...) cat(format(Sys.time(),"%H:%M:%S"),"|",...,"\n")
CC <- file.path(REV,"cache/v7/cc")
X <- Matrix::readMM(file.path(CC,"X.mtx"))
rownames(X) <- readLines(file.path(CC,"genes.csv"))
colnames(X) <- readLines(file.path(CC,"cells.csv"))
lab <- readLines(file.path(CC,"labels.csv"))
stopifnot(length(lab)==ncol(X), !any(duplicated(rownames(X))))
msg("CellChat input:", nrow(X), "genes x", ncol(X), "cells")
print(table(lab))
meta <- data.frame(labels=factor(lab), row.names=colnames(X))
cc <- createCellChat(object=X, meta=meta, group.by="labels")
cc@DB <- CellChatDB.human
msg("CellChatDB.human interactions:", nrow(CellChatDB.human$interaction))
cc <- subsetData(cc)
options(future.globals.maxSize = 8*1024^3)
future::plan("sequential")
cc <- identifyOverExpressedGenes(cc)
cc <- identifyOverExpressedInteractions(cc)
cc <- computeCommunProb(cc, type="triMean", population.size=TRUE)
cc <- filterCommunication(cc, min.cells=10)
cc <- computeCommunProbPathway(cc)
cc <- aggregateNet(cc)
df <- subsetCommunication(cc)
fwrite(as.data.table(df), file.path(OUT,"sc_cellchat_all_LR.csv"))
msg("CellChat LR communications:", nrow(df))
dfp <- subsetCommunication(cc, slot.name="netP")
fwrite(as.data.table(dfp), file.path(OUT,"sc_cellchat_pathways.csv"))
msg("CellChat pathway-level rows:", nrow(dfp))

cafs <- grep("^CAF|Myofib", levels(meta$labels), value=TRUE)
sub <- as.data.table(df)[source %in% cafs & target=="Cancer cell"]
setorder(sub, -prob)
fwrite(sub, file.path(OUT,"sc_cellchat_CAF_to_cancer.csv"))
msg("CAF -> cancer-cell LR pairs:", nrow(sub))
msg("=== top 25 CAF -> cancer cell by communication probability ===")
print(head(sub[, .(source, target, ligand, receptor, interaction_name_2, pathway_name, prob, pval)], 25))
subp <- as.data.table(dfp)[source %in% cafs & target=="Cancer cell"]
setorder(subp, -prob)
fwrite(subp, file.path(OUT,"sc_cellchat_CAF_to_cancer_pathways.csv"))
msg("=== CAF -> cancer cell, aggregated by signalling pathway (top 20) ===")
print(head(subp[, .(pathway=pathway_name, prob=round(prob,5)), by=.(source,target)][order(-prob)], 20))
msg("=== total CAF->cancer probability by pathway, summed over CAF subtypes ===")
print(subp[, .(total_prob=sum(prob), n_subtypes=uniqueN(source)), by=pathway_name][order(-total_prob)][1:25])
msg("=== COLLAGEN and TGFb pathways specifically ===")
print(subp[pathway_name %in% c("COLLAGEN","TGFb","LAMININ","FN1","THBS","TENASCIN","MK","PTN")][order(-prob)][1:30])
msg("DONE 36")
