#!/usr/bin/env python3
"""Consolidated record of the independent verification pass over PART 1 (screens) and
PART 2 (single cell).  Every value here was produced by a command in the verification scripts 40-48 (scripts/13_multiomics_and_screens/drug_and_crispr_screens and scripts/08_stroma_and_cell_types/single_cell)."""
import pandas as pd
REV="/path/to/revision"; OUT=f"{REV}/results/v3"
rows=[
("1A DEMETER2","82 breast lines (34 Achilles / 25 DRIVE / 76 Marcotte); 17,309 genes x 712 lines; 0 duplicate symbols","REPRODUCED EXACTLY","scripts/13_multiomics_and_screens/drug_and_crispr_screens/40_verify_screens_rnai.py"),
("1A DEMETER2","focus-gene mean D2 in breast lines: NFKB1 -0.0413, RELA -0.1542, SP1 -0.2975, ETS1 -0.0045, COL1A1 +0.0253, COL3A1 -0.0043, MYC -0.4191","REPRODUCED EXACTLY (all 7 to 4 dp)","scripts/13_multiomics_and_screens/drug_and_crispr_screens/40_verify_screens_rnai.py"),
("1A DEMETER2","controls behave: RPL7 -1.350, EIF3B -1.423, POLR2A -1.293, PSMA1 -1.067 vs PTEN -0.003, CDKN2A +0.068","VERIFIED","scripts/13_multiomics_and_screens/drug_and_crispr_screens/40_verify_screens_rnai.py"),
("1A DEMETER2","CRISPR-vs-RNAi genome-wide concordance over 15,443 shared genes: Spearman 0.2592, Pearson 0.6566","REPRODUCED EXACTLY","scripts/13_multiomics_and_screens/drug_and_crispr_screens/40_verify_screens_rnai.py"),
("1A DEMETER2","set-level vs expression-decile-matched null, 10 sets: observed means identical to 5 dp; null means agree to <=0.0012 (Monte-Carlo); every empirical p reproduced","REPRODUCED","scripts/13_multiomics_and_screens/drug_and_crispr_screens/41_verify_setlevel_null.py"),
("1B ProjectSCORE","sign convention confirmed: RPL7 +11.80, PSMA1 +14.98, RPL5 +14.56 vs PTEN -4.34, CDKN2A -3.34 => POSITIVE scaled Bayes factor = fitness gene","VERIFIED","scripts/13_multiomics_and_screens/drug_and_crispr_screens/42_verify_projectscore.py"),
("1B ProjectSCORE","43 unique QC-passing breast models, screened 63 times (20 models screened twice, Sanger and Broad)","CAVEAT: deposited run silently used the FIRST screen per model","scripts/13_multiomics_and_screens/drug_and_crispr_screens/42b_verify_projectscore_replicates.py"),
("1B ProjectSCORE","per-model averaging over all 63 screens vs first-screen-only: Spearman 0.9908 / Pearson 0.9984 over 17,645 genes; no focus-gene call changes","IMMATERIAL - deposited values stand","scripts/13_multiomics_and_screens/drug_and_crispr_screens/42b_verify_projectscore_replicates.py"),
("1B ProjectSCORE","focus genes, first-screen policy: COL1A1 -3.581, COL3A1 -3.628, ETS1 -2.992, NFKB1 -2.398, RELA -1.597, SP1 -2.483, STAT3 -4.222, HIF1A -4.503, TP53 -3.303, MYC +10.914, ESR1 +0.454","REPRODUCED EXACTLY","scripts/13_multiomics_and_screens/drug_and_crispr_screens/42b_verify_projectscore_replicates.py"),
("1C GDSC2","285 drugs x 47 breast lines, 1,425 tests; max |d rho| vs deposited 5.6e-16","REPRODUCED EXACTLY","scripts/13_multiomics_and_screens/drug_and_crispr_screens/43_verify_drug.py"),
("1C GDSC2","single survivor at within-score BH<0.05: Sinularin vs COLLAGEN score, rho +0.628, n=38, BH 0.0068; it ALSO survives global BH across all 1,425 tests (0.0341)","VERIFIED and STRENGTHENED","scripts/13_multiomics_and_screens/drug_and_crispr_screens/43_verify_drug.py"),
("1C GDSC2","direction: positive rho with LN_IC50 = collagen-high lines are MORE RESISTANT; Sinularin is an unclassified marine natural product with no annotated target","INTERPRETATION - not a therapeutic lead","scripts/13_multiomics_and_screens/drug_and_crispr_screens/43_verify_drug.py"),
("1C PRISM","1,440 compounds x 22 breast lines, 7,200 tests; max |d rho| vs deposited 6.7e-16; ZERO survivors at within-score BH<0.05 and ZERO at global BH<0.05","REPRODUCED EXACTLY","scripts/13_multiomics_and_screens/drug_and_crispr_screens/43b_verify_prism.py"),
("1C module scores","COLLAGEN cell-line score re-derived from DepMap 24Q4: max |difference| 3.8e-15","REPRODUCED EXACTLY","scripts/13_multiomics_and_screens/drug_and_crispr_screens/43_verify_drug.py"),
("1C module scores","COL11A1 was DROPPED from the 9-gene collagen score (detected in only 4.3% of breast lines); the cell-line COLLAGEN score is an 8-gene score","CAVEAT worth stating - COL11A1 is a myCAF marker absent from carcinoma lines","scripts/13_multiomics_and_screens/drug_and_crispr_screens/43_verify_drug.py"),
("1D ORCS","BioGRID ORCS 2.0.18: 1,952 human screens; 140 breast/mammary; phenotypes 97 proliferation, 30 response-to-chemicals, 8 tumorigenicity, 2 protein accumulation, 2 viability, 1 radiation","REPRODUCED EXACTLY","scripts/13_multiomics_and_screens/drug_and_crispr_screens/43c_verify_orcs.py"),
("1D ORCS","ZERO breast screens with a migration, invasion or ECM phenotype. The only 2 migration-phenotype screens in the whole human database are glioblastoma U-138MG (PMID 31570734) and forebrain assembloids (PMID 37758944)","VERIFIED - clean negative","scripts/13_multiomics_and_screens/drug_and_crispr_screens/43c_verify_orcs.py"),
("1D ORCS","raw hit calls spot-checked in screens 188/220/222: MYC HIT=YES in all three; NFKB1, COL1A1, RELA HIT=NO; hit counts and rates match deposited","VERIFIED","scripts/13_multiomics_and_screens/drug_and_crispr_screens/43c_verify_orcs.py"),
("1D ORCS","across 99 breast proliferation screens: MYC hit in 71, ESR1 in 15, SP1 in 6, RELA in 3, ETS1 in 2, MKL1 in 1; NFKB1, COL1A1, COL3A1, STAT3, HIF1A and MMP2 hit in ZERO","VERIFIED from deposited gene-level table","results/v3/screens_orcs_focus_gene_hitrates.csv"),
("1E integrated","587 nodes: 1 essential in every modality tested (YY1), 26 in some, 337 non-essential in every modality, 223 miRNAs not screenable","REPRODUCED EXACTLY","scripts/13_multiomics_and_screens/drug_and_crispr_screens/44b_verify_integrated_matrix.py"),
("1E integrated","60 FFL hubs: 35 screened, MYC is the only one essential in any modality","REPRODUCED EXACTLY","scripts/13_multiomics_and_screens/drug_and_crispr_screens/44b_verify_integrated_matrix.py"),
("1E integrated","cross-modality Spearman over the 353 nodes with all three: CRISPR-RNAi +0.161, CRISPR-SCORE -0.812 (opposite sign conventions), RNAi-SCORE -0.131","REPRODUCED EXACTLY","scripts/13_multiomics_and_screens/drug_and_crispr_screens/44b_verify_integrated_matrix.py"),
("2F atlas","the second atlas is a CELLxGENE-integrated 8-study breast object, 621,200 cells x 37,389 genes: pal_2021 224,823; wu_natgen_2021 99,876; tietscher_2023 97,301; bassez_2021 78,549; wang_2024 48,553; qian_2020 40,665; liu_2023 27,490; gao_2021 3,943","VERIFIED - covers both atlases the task named","scripts/08_stroma_and_cell_types/single_cell/44_verify_sc_atlas.py"),
("2F atlas","pseudobulk was correctly built from raw/X integer counts, not the log-normalised X","VERIFIED","scripts/08_stroma_and_cell_types/single_cell/44_verify_sc_atlas.py"),
("2F atlas","COL1A1 fibroblast-over-malignant fold, 7 studies excluding Wu: median 367.9x (range 116.5-809.7); COL3A1 median 391.7x (range 129.3-2170.8)","REPRODUCED (independent streaming pass)","scripts/08_stroma_and_cell_types/single_cell/44_verify_sc_atlas.py"),
("2F atlas","Pal et al. 2021 alone: COL1A1 13,907.6 vs 38.1 CPM = 365.4x; COL3A1 8,528.6 vs 21.2 = 403.0x; EPCAM reversed 8.0 vs 248.8 CPM confirms the labels","REPRODUCED EXACTLY","scripts/08_stroma_and_cell_types/single_cell/44_verify_sc_atlas.py"),
("2G CAF subtypes","HBCA COL1A1 CPM by subtype: CAFs(LAMP5) 26,373.1; CAFs(COL11A1+) 21,248.0; CAFs(PI16+) 10,878.1; CAFs(CA12+) 6,802.9; CAFs(DPT+) 3,629.4; Myofibroblast 1,129.3; malignant 34.1","REPRODUCED EXACTLY","scripts/08_stroma_and_cell_types/single_cell/44_verify_sc_atlas.py"),
("2G CAF subtypes","Wu et al.: myCAF-like COL1A1 16,093.0 vs MSC iCAF-like 3,303.3 CPM = 4.87x; COL3A1 9,477.7 vs 2,694.1 = 3.52x; COL11A1 553.1 vs 69.9 = 7.9x","VERIFIED - collagen is a myCAF programme","results/v3/sc_wu_caf_focus_genes_cpm.csv"),
("2G CAF subtypes","TF-vs-COL1A1 across the 6 CAF subtypes: only RUNX2 nominally significant (rho +0.943, p=0.0048), but n=6 subtypes and 13 TFs tested -> BH-adjusted p = 0.0625","CAVEAT: this sub-analysis survives nothing after correction","results/v3/sc_caf_subtype_TF_vs_collagen.csv"),
("2G CAF subtypes","collagen is NOT CAF-exclusive: Wu PVL_Immature 1,895 CPM and Cycling_PVL 2,895 CPM COL1A1; HBCA PCs(ECM) carry a high collagen-programme score","CAVEAT worth stating","results/v3/sc_wu_caf_focus_genes_cpm.csv"),
("2H segregation","CIRCULARITY CONFIRMED: in TCGA-BRCA (n=1,066), miR-29 is NEGATIVELY correlated with fibroblast content in 16 of 16 deconvolution features (median rho -0.258) while miR-130a-3p is POSITIVELY correlated in 16 of 16 (median rho +0.095)","NEW - this is what drives the apparent segregation","scripts/08_stroma_and_cell_types/single_cell/45_circularity_check.R"),
("2H segregation","de-circularised: sets rebuilt from partial correlations adjusting for CAF and Cancer-Epithelial fractions. miR-130a anti-correlated set goes from malignant z=+10.8 to z=+3.3 and from fibroblast z=+1.4 to z=+3.3","CORRECTION","scripts/08_stroma_and_cell_types/single_cell/46_compartment_decircularised.R,47"),
("2H segregation","formal two-set contrast (miR-29 minus miR-130a), label permutation: MALIGNANT-share difference -0.0194 (p=0.0002) raw -> -0.0013 (p=0.74) adjusted; FIBROBLAST-share difference +0.0884 (p=0.0002) raw -> +0.0293 (p=0.0006) adjusted","CORRECTION - the epithelial half of the claim does not survive","scripts/08_stroma_and_cell_types/single_cell/47_compartment_test_decirc.py"),
("2H segregation","non-circular database-derived sets: mir29_strong vs mir130a_strong fibroblast difference +0.0076 (p=0.81); TargetScan-conserved +0.0228 (p=0.0018). BOTH miRNAs' target sets are fibroblast-enriched over null (z=3.1 to 10.1); NEITHER is malignant-enriched","CORRECTION","scripts/08_stroma_and_cell_types/single_cell/47_compartment_test_decirc.py"),
("2I CellChat","CAF -> cancer pathway totals: COLLAGEN 1.128e-02, MK 2.048e-03, FN1 1.949e-03, THBS 1.288e-03, LAMININ 6.063e-04; independent replicate run (21,811 cells, nboot=50) gives COLLAGEN 1.112e-02","REPRODUCED EXACTLY","scripts/08_stroma_and_cell_types/single_cell/49_verification_summary.py"),
("2I CellChat","TGF-beta: exactly 8 pathway-level communications in the whole atlas (20 at ligand-receptor level), ALL targeting CAFs (LAMP5); ZERO into cancer cells","REPRODUCED EXACTLY","scripts/08_stroma_and_cell_types/single_cell/49_verification_summary.py"),
("2I CellChat","the receptor explanation is real: TGFBR2 5.9 CPM in malignant cells vs 80.7-213.2 CPM across the five CAF subsets (independent streaming pass)","REPRODUCED EXACTLY","scripts/08_stroma_and_cell_types/single_cell/44_verify_sc_atlas.py"),
("2I LIANA","rank_aggregate cross-check: 34 CAF->cancer pairs in the top 1% of magnitude rank, 18 of them collagen ligands; best collagen rank 0.0013 vs best TGF-beta 0.0213; receptors CD44 (20), SDC4 (7), CD63 (4)","REPRODUCED EXACTLY","scripts/08_stroma_and_cell_types/single_cell/49_verification_summary.py"),
("2I CellChat","CAVEAT: CellChat communication probability is a mass-action function of ligand abundance, and collagens are the most abundant transcripts in CAFs by orders of magnitude, so COLLAGEN topping the list is partly built in. The rank-based LIANA result is the safer citation","CAVEAT","-"),
("2J within-CAF","myCAF-like fraction vs CAF COL1A1 across 104 donors: rho +0.615, p=3.9e-12 - CAF-subtype composition is a major within-compartment confound, mirroring the bulk problem","VERIFIED","scripts/08_stroma_and_cell_types/single_cell/48_verify_within_caf.R"),
("2J within-CAF","after adjusting for study AND myCAF-like fraction, only RUNX1 (+0.296, BH 0.031), SRF (+0.293, BH 0.031) and RUNX2 (+0.267, BH 0.050) remain positively associated with COL1A1 inside CAFs; max |difference| vs deposited 2.6e-16","REPRODUCED EXACTLY","scripts/08_stroma_and_cell_types/single_cell/48_verify_within_caf.R"),
("2J within-CAF","ETS1 -> COL1A1, the manuscript's flagship TF edge: TCGA bulk rho +0.284 (FDR ~0) but within-CAF rho -0.078 (FDR 0.51), study-adjusted +0.034, fully adjusted -0.055 (p=0.58). It does not exist inside the CAF compartment","KEY RESULT","scripts/08_stroma_and_cell_types/single_cell/48_verify_within_caf.R"),
("2J within-CAF","NFKB1 -> COL1A1 REVERSES: bulk +0.129 vs within-CAF -0.266 (FDR 0.014); fully adjusted -0.080 (p=0.42)","KEY RESULT","scripts/08_stroma_and_cell_types/single_cell/48_verify_within_caf.R"),
("2J within-CAF","CAVEAT: the strong raw NEGATIVE within-CAF correlations of JUN (-0.525), FOS (-0.518) and EGR1 (-0.599) with COL1A1 are immediate-early genes and are a known dissociation-stress artefact; all three attenuate to non-significance after adjustment","CAVEAT","scripts/08_stroma_and_cell_types/single_cell/48_verify_within_caf.R"),
]
S=pd.DataFrame(rows,columns=["part","item","verdict","source"])
S.to_csv(f"{OUT}/screens_sc_verification_summary.csv",index=False)
print(S.to_string(index=False)[:200])
print("\nrows:",len(S))
print("verdict counts:"); print(S.verdict.str.split(" ").str[0].value_counts().to_string())
